### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [bensteinberg/samuel-r-delany_the-jewels-of-aptor#1]
### General Issues:

- [x] **MAKE THIS CHANGE FIRST!** The commit `[Editorial] Remove italicization from poetry` should not be an editorial commit. You can change the commit message by running `git rebase -i HEAD~10`. If you need further instructions on how to rebase, feel free to let me know. 

- [x] The `xml:lang` attribute is for foreign languages. Use `<q>`s for telepathy.

- [x] We avoid using classes that are only used a couple of times. Remove `class="signage"` and `class="continued signage"`. For the CSS, you can target the specific blockquotes in the chapters.

- [x] Create a se-lint-ignore.xhtml file and ignore error `t-011`.

- [x] Re-run `se typogrify .` and commit the changes.

### epigraph.xhtml:

- [x] `—These are the opening lines from <i epub:type="se:name.publication.book">The Galactica</i>, by the one-armed poet Geo, the epic of the conflicts of Leptar and Aptor.`
The poem's quote source needs to be in a `<cite>` element without a leading em dash and without a trailing period. See [SEMOS 7.4.5.1](https://standardebooks.org/manual/1.7.0/single-page#7.4.5.1) on how it should look.

### chapter-5.xhtml:

- [x] In `<p>N .. SM .. K .. G</p>`, you can convert the two periods into ellipses.

### chapter-7.xhtml:

- [x] `WMTH` looks like an abbreviation. See [SEMOS 8.10.2](https://standardebooks.org/manual/1.7.0/single-page#8.10.2) on how to format initialisms.

### chapter-8.xhtml:

- [x] The "Hymn to the Goddess Argo" needs `z3998:hymn` semantics

- [x] The hymn title:
```
				<p>
					<span>
						<i epub:type="se:name.publication.poem">Hymn to the Goddess Argo</i>
					</span>
				</p>
```
needs to be in a `<header>`. See [SEMOS 7.2.10.8](https://standardebooks.org/manual/1.7.0/single-page#7.2.10.8) on how the title should be formatted. Remove `epub:type="se:name.publication.poem"`.

**Comment by bensteinberg** [comment]
Thanks! I believe I've now addressed all of these items. Please let me know if I've missed anything. I can associate commits with the check boxes, but the commit messages should be pretty clear.

**Comment by EmmaSweeney** [comment]
- [ ] WMTH needs periods between the letters.

- [ ] Add `class="eoc"` to the initialisms that are followed by periods.

- [x] You're missing some epigraph CSS. You can copy the CSS from [SEMOS 7.4.1](https://standardebooks.org/manual/1.7.0/single-page#7.4.1).

- [ ] Remove `class="continued"` from the `<blockquote>` in chapter 7. This class is only applied to paragraphs.

**Comment by bensteinberg** [comment]
> WMTH needs periods between the letters.

That is a U.S. radio station call sign, which is never rendered with periods, and now that I think of it, is not really an initialism. If there isn't a standard for marking up call signs, I'd be inclined to remove the markup.

**Comment by bensteinberg** [comment]
> Remove `class="continued"` from the `<blockquote>` in chapter 7. This class is only applied to paragraphs.

I can remove it, but I still need a way to differentiate that blockquote from the one preceding it. In [the relevant section of local.css](https://github.com/bensteinberg/samuel-r-delany_the-jewels-of-aptor/blob/0c18c8703a6b2dcf9642422babea032b6fe69bc5/src/epub/css/local.css#L37-L46), I'm handling two different situations where, in the text, a sign has a main part ["and beneath it, in smaller letters"](https://github.com/bensteinberg/samuel-r-delany_the-jewels-of-aptor/blob/0c18c8703a6b2dcf9642422babea032b6fe69bc5/src/epub/text/chapter-7.xhtml#L28) a secondary part. In [the first case](https://github.com/bensteinberg/samuel-r-delany_the-jewels-of-aptor/blob/0c18c8703a6b2dcf9642422babea032b6fe69bc5/src/epub/text/chapter-7.xhtml#L25-L31), this one, there are two separate blockquotes, and [in the second case](https://github.com/bensteinberg/samuel-r-delany_the-jewels-of-aptor/blob/0c18c8703a6b2dcf9642422babea032b6fe69bc5/src/epub/text/chapter-7.xhtml#L44-L49), a single blockquote containing two `<p>` tags. The second `<p>` in the latter case is easy to target, but in order to target the second part of the first sign, I think I need a class. Can you suggest an alternative?

**Comment by EmmaSweeney** [comment]
>> WMTH needs periods between the letters.

> That is a U.S. radio station call sign, which is never rendered with periods, and now that I think of it, is not really an initialism. If there isn't a standard for marking up call signs, I'd be inclined to remove the markup.

If this is call sign then it is an alphanumeric designation and doesn't receive semantics.

>> Remove class="continued" from the `<blockquote>` in chapter 7. This class is only applied to paragraphs.

>I can remove it, but I still need a way to differentiate that blockquote from the one preceding it. In [the relevant section of local.css](https://github.com/bensteinberg/samuel-r-delany_the-jewels-of-aptor/blob/0c18c8703a6b2dcf9642422babea032b6fe69bc5/src/epub/css/local.css#L37-L46), I'm handling two different situations where, in the text, a sign has a main part ["and beneath it, in smaller letters"](https://github.com/bensteinberg/samuel-r-delany_the-jewels-of-aptor/blob/0c18c8703a6b2dcf9642422babea032b6fe69bc5/src/epub/text/chapter-7.xhtml#L28) a secondary part. In [the first case](https://github.com/bensteinberg/samuel-r-delany_the-jewels-of-aptor/blob/0c18c8703a6b2dcf9642422babea032b6fe69bc5/src/epub/text/chapter-7.xhtml#L25-L31), this one, there are two separate blockquotes, and [in the second case](https://github.com/bensteinberg/samuel-r-delany_the-jewels-of-aptor/blob/0c18c8703a6b2dcf9642422babea032b6fe69bc5/src/epub/text/chapter-7.xhtml#L44-L49), a single blockquote containing two `<p>` tags. The second `<p>` in the latter case is easy to target, but in order to target the second part of the first sign, I think I need a class. Can you suggest an alternative?

You can target that specific blockquote in the chapter for styling by using `#chapter-7 blockquote:nth-child(2){ }`

**Comment by bensteinberg** [comment]
Thanks! I've removed the semantics from the call sign, and I'm still working on the styling.

**Comment by bensteinberg** [comment]
I think I've got the styling for signage right now, in 6c008d2. Thanks for the help with targeting! Please let me know if you see anything else that needs work.
